### ISSUE TITLE
Student server webhook improvements

### ISSUE THREAD

**Issue by itislu** [42-student-council/website#172]
- [ ] Add `open` and `archived` tags to the the forum and apply accordingly.
   #174
- [x] Differentiate official student council answers also on Discord.
   #175
- [x] `#N` in the URL of the notification, so that opening the notification brings you directly to the new comment.
   #183

**Comment by leeoocca** [comment]
Another cool feature would be to add a `#N` in the URL of the notification, so that opening the notification brings you directly to the new comment.
