### ISSUE TITLE
Idea: Upvote color change

### ISSUE THREAD

**Issue by poechlauerbe** [42-student-council/website#63]
If I click on upvote the color of the button could change (maybe some lightgreen)

**Comment by winstonallo** [comment]
good idea:)

**Comment by itislu** [comment]
I agree, atm you cannot know if you already upvoted something or not.
Having to press the button to see if the number goes down or up is bad UX.

**Comment by winstonallo** [comment]
> If I click on upvote the color of the button could change (maybe some lightgreen)

@poechlauerbe can you look at #73 and tell me if that's what you meant? If yes we can merge it :) Thanks for your issue!!

**Comment by poechlauerbe** [comment]
yes, exactly :+1:
