### ISSUE TITLE
Only one issue column on mobile in vertical mode

### ISSUE THREAD

**Issue by itislu** [42-student-council/website#81]
There's only the title column on the Issues page.
It's not possible to scroll to the right.

That means the issues cannot be sorted manually.

Vertical:
![Screenshot_20240709_210007_Chrome.jpg](https://github.com/42-student-council/website/assets/129603980/85b74003-7ed9-4ec4-b030-390ece8dfc95)

Horizontal:
![Screenshot_20240709_210017_Chrome.jpg](https://github.com/42-student-council/website/assets/129603980/bc428172-fbe3-4284-82ae-5abb3466ddfb)

**Comment by ifaoji** [comment]
Yes and no.

The problem is that on mobile view the entire table would get too large. Therefore the other fields are hidden currently.

Overflowing the page would also not really be a nice to have solution. I'm open to ideas.

**Comment by itislu** [comment]
How about making the table itself horizontally scrollable?
So still keep the box where the table is in to not overflow, but the table itself within that box can overflow.

**Comment by ifaoji** [comment]
Or actually it's not that bad. What do you think?
![image](https://github.com/42-student-council/website/assets/58186924/f93acc83-8864-428c-96ad-7962f45be351)

**Comment by itislu** [comment]
Oh cool. It looks fine to me.
I'll ask the other members.

**Comment by itislu** [comment]
@ifaoji Ok so everyone approved your latest image.
If you are fine with it too, you can implement it :)
